DO NOT MERGE
PINCODE-project/proveryaka pull request #27
Opened 2024-10-21 15:42 UTC by CatDevelop

2024-10-26 16:44 UTC, IrkaTyman requested changes

2024-10-26 16:44 UTC, IrkaTyman commented on frontend/src/entities/issue-draft/api/getMyIssueDraft.ts
> +export function getMyIssueDraft(spaceId: string): Promise<GetIssueDraftResponse | void> {
Тут точно нужен войд? Как будто надо избежать такой ситуации

2024-10-26 16:44 UTC, IrkaTyman commented on frontend/src/entities/issue/lib/getSpaceIssueCountQueryKey.ts
> +    return ['space-issue/get-count', spaceId, filters].filter(Boolean) as (string|ListFilters)[];
Без as не работает?

2024-10-26 16:44 UTC, IrkaTyman commented on frontend/src/entities/issue/lib/getSpaceIssueQueryKey.ts
> +    isDesc?: boolean,
Как буто надо выделить это в тип сортировки по аналогии с filters

Пример: sorting?: ListSorting

2024-10-26 16:44 UTC, IrkaTyman commented on frontend/src/entities/issue/model/GetIssueResponse.ts
> +    status?: IssueStatus;
Лучше подтянуть дев, возможны конфликты. Актуальный тип указывала в другой ветке, уже слито

2024-10-26 16:44 UTC, IrkaTyman commented on frontend/src/entities/issue/ui/IssuesTable/IssuesTable.module.css
> +}
Лишние стили

2024-10-26 16:44 UTC, IrkaTyman commented on frontend/src/entities/issue/ui/IssuesTable/IssuesTable.tsx
> +    changeFilters: (key: ('page' | 'count' | 'isDistributed'), name: (number | undefined)) => void;
Лучше использовать какой-то тип, а не перечислять вручную поля

2024-10-26 16:44 UTC, IrkaTyman commented on frontend/src/entities/issue/ui/IssuesTable/IssuesTable.tsx
> +    changeFilters: (key: ('page' | 'count' | 'isDistributed'), name: (number | undefined)) => void;
А зачем типы взяты в скобки?

2024-10-26 16:44 UTC, IrkaTyman commented on frontend/src/entities/issue/ui/IssuesTable/IssuesTable.tsx
> +    changeFilters: (key: ('page' | 'count' | 'isDistributed'), name: (number | undefined)) => void;
Наверное, не name, а value

2024-10-26 16:44 UTC, IrkaTyman commented on frontend/src/entities/issue/ui/IssuesTable/IssuesTable.tsx
> +                render: (value: string) => new Date(value).toLocaleString('ru-RU', {
getDateByISO - общая функция из shared

2024-10-26 16:44 UTC, IrkaTyman commented on frontend/src/entities/issue/ui/IssuesTable/IssuesTable.tsx
> +                render: (value: string) => new Date(value).toLocaleString('ru-RU', {
getDateByISO - общая функция из shared

2024-10-26 16:44 UTC, IrkaTyman commented on frontend/src/entities/issue/ui/IssuesTable/IssuesTable.tsx
> +        } else {
Можно не прописывать условия добавления столбца в массив, а собрать массив из всех столбцов, но указать параметр hidden, выглядит аккуратнее

2024-10-26 16:44 UTC, IrkaTyman commented on frontend/src/entities/user/api/getUserIsOrganizer.ts
> +    return res.data['http://schemas.microsoft.com/ws/2008/06/identity/claims/role'] === 'admin';
А для чего это было сделано?) Выбивается из общего формата запросов

2024-10-26 16:44 UTC, IrkaTyman commented on frontend/src/features/issue/create-issue/api/deleteMyDraft.ts
> +export function deleteMyDraft(spaceId: string) {
Что возвращает функция?

2024-10-26 16:44 UTC, IrkaTyman commented on frontend/src/features/issue/create-issue/ui/CreateIssueCriteriaForm/CreateIssueCriteriaForm.module.css
> +    font: var(--font-default);
Лучше не задавать, так как определеяется стилями анта (там другой шрифт)

2024-10-26 16:44 UTC, IrkaTyman commented on frontend/src/features/issue/create-issue/ui/CreateIssueCriteriaForm/CreateIssueCriteriaForm.module.css
> +    font: var(--font-default);
Лучше не задавать, так как определеяется стилями анта (там другой шрифт)

2024-10-26 16:44 UTC, IrkaTyman commented on frontend/src/features/issue/create-issue/ui/CreateIssueFormForm/CreateIssueFormForm.module.css
> +    font: var(--font-default);
Лучше не задавать, так как определеяется стилями анта (там другой шрифт)

2024-10-26 16:44 UTC, IrkaTyman commented on frontend/src/features/issue/create-issue/ui/CreateIssueFormForm/CreateIssueFormForm.module.css
> +}
Отступ

2024-10-26 16:44 UTC, IrkaTyman commented on frontend/src/features/issue/create-issue/ui/CreateIssueFormForm/CreateIssueFormForm.module.css
> +    padding-bottom: 20px !important;
Можно ли обойтись без !important?

2024-10-26 16:44 UTC, IrkaTyman commented on frontend/src/features/issue/create-issue/ui/CreateIssueFormForm/CreateIssueFormForm.tsx
> +    const getIssueFormButtons = (
Тяжело читаются функции, которые возвращают компонент внутри компонента. Можно вынести в отдельные компоненты в файлы рядом

2024-10-26 16:44 UTC, IrkaTyman commented on frontend/src/features/issue/create-issue/ui/CreateIssueGeneralForm/CreateIssueGeneralForm.module.css
> +    font: var(--font-default);
Писала про font выше

2024-10-26 16:44 UTC, IrkaTyman commented on frontend/src/features/issue/create-issue/ui/CreateIssueGeneralForm/CreateIssueGeneralForm.tsx
> +};
Отступ

2024-10-26 16:44 UTC, IrkaTyman commented on frontend/src/pages/space/SpaceCreateIssuePage/SpaceCreateIssuePage.tsx
> +    const handleChangeStep = useCallback(async (step: number) => {
Этот метод будто лучше разбить на составные с понятными названиями, чтобы метод был поэтапным (читается трудно). Чисто пожелание

2024-10-26 16:44 UTC, IrkaTyman commented on frontend/src/pages/space/SpaceCreateIssuePage/SpaceCreateIssuePage.tsx
> +    const CreateIssueButtons = useMemo(() => {
Вынести в отдельный файл

2024-10-26 16:44 UTC, IrkaTyman commented on frontend/src/pages/space/SpaceCreateIssuePage/SpaceCreateIssuePage.tsx
> +    const CreateIssueForm = useMemo(() => {
Вынести в отдельный файл

2024-10-26 16:44 UTC, IrkaTyman commented on frontend/src/pages/space/SpaceIssuePage/SpaceIssuePage.tsx
> +        );
Можно через hdden: boolean, чтобы не было условий с большим телом

2024-10-26 16:44 UTC, IrkaTyman commented on frontend/src/pages/space/SpacePage/subpages/SpaceIssuesPage/SpaceIssuesPage.tsx
> +        if (record.status === 0) {
Можно убрать условия, используя hidden: boolean

2024-10-26 16:44 UTC, IrkaTyman commented on frontend/src/pages/space/SpacePage/subpages/SpaceIssuesPage/SpaceIssuesPage.tsx
> +    const SpaceIssuesButton = useMemo(() => {
В отдельный компонент бы

2024-10-26 16:44 UTC, IrkaTyman commented on frontend/src/shared/styles/variables.css
> +    --title-2-line-height: 28px/36px;
Оба исправленные свойства можно удалить. Нейминг исправлен, а значения - нет

2024-10-27 13:15 UTC, CatDevelop commented on frontend/src/entities/issue/lib/getSpaceIssueCountQueryKey.ts
> +    return ['space-issue/get-count', spaceId, filters].filter(Boolean) as (string|ListFilters)[];
Не работает

2024-10-27 13:15 UTC, CatDevelop commented on frontend/src/entities/issue/model/GetIssueResponse.ts
> +    status?: IssueStatus;
Дев подтянут

2024-10-27 19:02 UTC, CatDevelop commented on frontend/src/entities/user/api/getUserIsOrganizer.ts
> +    return res.data['http://schemas.microsoft.com/ws/2008/06/identity/claims/role'] === 'admin';
Хз, я не трогал 😐

2024-10-27 19:39 UTC, CatDevelop commented on frontend/src/pages/space/SpacePage/subpages/SpaceIssuesPage/SpaceIssuesPage.tsx
> +        if (record.status === 0) {
В dropdown items нет поля hidden

2024-11-01 07:32 UTC, IrkaTyman approved these changes

2024-11-01 09:20 UTC, merged